spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    spring-security:
      enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
  security:
    oauth2:
      client:
        registration:
          google:
            clientid: aa
            clientsecret: aa
            scope:
              - email
              - profile
jwt:
  issuer: ajufresh@gmail.com
  secretkey: study-springboot
admin:
  email: pnuiba514@gmail.com