INSERT INTO article (title, content,author, created_at, updated_at, category) VALUES ('박준형', '박준형','user1', NOW(), NOW(), '개인')
INSERT INTO article (title, content,author, created_at, updated_at, category) VALUES ('박준형', '박준형','user2', NOW(), NOW(), '개인')
INSERT INTO article (title, content,author, created_at, updated_at, category) VALUES ('박준형', '박준형','user3', NOW(), NOW(), '개인')
INSERT INTO article (title, content,author, created_at, updated_at, category) VALUES ('박준형', '박준형','user4', NOW(), NOW(), '개인')
INSERT INTO article (title, content,author, created_at, updated_at, category) VALUES ('박준형', '박준형','user5', NOW(), NOW(), '개인')
